### ISSUE TITLE
Allow export of first-n best haplogroups

### ISSUE THREAD

**Issue by haansi** [seppinho/haplogrep-cmd#12]
Add Parameter to export first n haplogroups with highest score

**Comment by stephenturner** [comment]
I'd upvote this feature if it's something you're still considering 👍

**Comment by afkoeppel** [comment]
Yes, this would be a great feature to have.

**Comment by seppinho** [comment]
Thanks for letting us know. Any preferred output format?

**Comment by stephenturner** [comment]
Thanks! Perhaps a typical "tidy" format, separate line for each sample-haplogroup combination. eg.

```
sample haplogroup rank prob
seppinho H1 1 .9
seppinho U 2 .8
stephenturner H1b1 1 .7
stephenturner U1 2 .6
stephenturner H3 3 .5
```

**Comment by stephenturner** [comment]
Awesome. Thanks @seppinho, and thanks for the suggestion @haansi, @afkoeppel, @punkrockscience. Going to try this one out immediately.

**Comment by seppinho** [comment]
great, just let me know.
