### ISSUE TITLE
Remove jbwa-xxxx folder after running HaploGrep

### ISSUE THREAD

**Issue by alexhbnr** [seppinho/haplogrep-cmd#33]
Hello,

After running HaploGrep2 on a Linux server using a FastA file as an input, HaploGrep2 successfully generates the HSD report file, but does not clean up the empty jbwa-xxxx folder.
If I run HaploGrep2 on a larger number of files, I have hundreds of empty folders at the location from which HaploGrep2 was called.

Here is the command I am using:
`java -Xms256m -Xmx1G -jar haplogrep-2.1.25.jar 
                 --in ${input} 
                 --extend-report 
                 --format fasta 
                 --hits 5 
                 --out ${output}`

Is this behaviour on purpose or could HaploGrep2 remove this folder automatically before shutting itself down?

**Comment by seppinho** [comment]
thanks. I will provide a fix. sorry for that!  How does the fasta converter work? Would be great if you have some eval results for us.

**Comment by alexhbnr** [comment]
The FastA converter works well, as far as I am aware. I used it on > 3,500 samples as part of a pipeline and it did not crash or give weird errors. However, I did not check whether I get the same results when using a different input format. Should I be concerned when using it?

**Comment by seppinho** [comment]
FASTA test cases looking good, I was just curious :) 
Regarding the reported issue: I checked the source and the jbwa directory should be deleted. It gets deleted on my Linux, did not change this for a while. Can you please double check using the latest version (see Readme). Thanks!

**Comment by alexhbnr** [comment]
Thanks, @seppinho, I tested the latest release (v2.2.5) and it works now fine.
