### ISSUE TITLE
can't install haplogrep-cmd

### ISSUE THREAD

**Issue by kopelol** [seppinho/haplogrep-cmd#43]
Hello everyone, 

I couldn't install haplogrep-cmd.

I used following code
`curl -sL haplogrep.now.sh | bash`

But I couldn't install 

> Downloading Haplogrep from https://github.com/seppinho/haplogrep-cmd/releases/download/v2.3.0/haplogrep.zip...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 

Could you give me some advice?

Regards,

**Comment by nuin** [comment]
@kopelol It seems that they changed the bash script and haven't released the version 2.3.0, as the latest release available here is 2.2.9.

```
NAME="Haplogrep"
VERSION="v2.3.0"
GITHUB_USER="seppinho"
GITHUB_REPO="haplogrep-cmd"
EXECUTABLE="haplogrep"
ZIP="haplogrep.zip"
```

second line should be `VERSION="v.2.2.9"`.

You could run 

`curl -sL haplogrep.now.sh`

without the pipe to bash, save the script, modify the line and then


`bash ./<script_name>`

or wait for them to release 2.3.0

**Comment by haansi** [comment]
thanks @nuin, that's correct, we still need to provide the update to version 2.3.0. In the meantime you can download the zip file in releases https://github.com/seppinho/haplogrep-cmd/releases/tag/v2.2.9 - download and extract

**Comment by kopelol** [comment]
@nuin and @haansi Thank you for your responses and advices.

I'll try it

Thank you.

**Comment by kopelol** [comment]
I've just installed haplogrep successfully.

Thank you for all of your help.

**Comment by seppinho** [comment]
`curl -sL haplogrep.now.sh | bash` works again.
