### ISSUE TITLE
Annotate FASTA file

### ISSUE THREAD

**Issue by nuin** [seppinho/haplogrep-cmd#6]
Hi

We know that web Haplogrep can annotate genomes in a FASTA file. Is it possible to do the same on the command line version?

Thanks

**Comment by seppinho** [comment]
Hi Paolo,
adding the --extend-report parameter should add the required information to the output.
best

**Comment by nuin** [comment]
But can I use a FASTa file as input? It asks me for hsd or vcf files.

Thanks again

**Comment by seppinho** [comment]
sorry my bad. thats an open issue. see #3

**Comment by nuin** [comment]
OK, thanks. I will close this one and follow #3
